# Generated by Django 5.0.6 on 2024-07-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_create_default_data_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog_tag_node_subclass', models.CharField(verbose_name='Analog Tag Node Subclass')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='StationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_node_id', models.PositiveIntegerField(help_text='Device Node ID', verbose_name='Device Node ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station')),
            ],
        ),
        migrations.CreateModel(
            name='StationParameterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog_tag_node_id', models.CharField(verbose_name='Analog Tag Node ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wis2box_adl_adcon_plugin.parametermapping', verbose_name='Parameter')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wis2box_adl_adcon_plugin.stationmapping', verbose_name='Station')),
            ],
        ),
    ]
