# Generated by Django 5.0.6 on 2024-10-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_node_id', models.PositiveIntegerField(help_text='ADCON Device Node', unique=True, verbose_name='ADCON Device Node')),
                ('last_imported', models.DateTimeField(blank=True, null=True, verbose_name='Last Imported')),
                ('station', models.OneToOneField(help_text='Station to link with ADCON', on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'ADCON Station Link',
                'verbose_name_plural': 'ADCON Stations Link',
            },
        ),
        migrations.CreateModel(
            name='StationParameterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog_tag_node_id', models.PositiveIntegerField(unique=True, verbose_name='Analog Tag Node ID')),
                ('units', models.CharField(default=None, max_length=10, verbose_name='Units')),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter')),
                ('station_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_parameter_mappings', to='wis2box_adl_adcon_plugin.stationmapping', verbose_name='Station Mapping')),
            ],
            options={
                'verbose_name': 'ADCON Station Parameter Mapping',
                'verbose_name_plural': 'ADCON Station Parameter Mapping',
                'ordering': ['station_mapping'],
            },
        ),
        migrations.AddConstraint(
            model_name='stationparametermapping',
            constraint=models.UniqueConstraint(fields=('station_mapping', 'parameter'), name='unique_station_mapping_parameter'),
        ),
    ]
