# Generated by Django 5.0.6 on 2024-10-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_station_wmo_block_number'),
        ('wis2box_adl_adcon_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationparametermapping',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter'),
        ),
    ]
