# Generated by Django 5.0.6 on 2024-07-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_network_plugin'),
        ('wis2box_adl_adcon_plugin', '0002_alter_parametermapping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermapping',
            name='analog_tag_node_subclass',
            field=models.CharField(unique=True, verbose_name='Analog Tag Node Subclass'),
        ),
        migrations.AlterField(
            model_name='parametermapping',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', unique=True, verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='stationmapping',
            name='device_node_id',
            field=models.PositiveIntegerField(help_text='Device Node ID', unique=True, verbose_name='Device Node ID'),
        ),
        migrations.AlterField(
            model_name='stationparametermapping',
            name='analog_tag_node_id',
            field=models.CharField(unique=True, verbose_name='Analog Tag Node ID'),
        ),
        migrations.AlterField(
            model_name='stationparametermapping',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wis2box_adl_adcon_plugin.parametermapping', unique=True, verbose_name='Parameter Mapping'),
        ),
        migrations.AlterField(
            model_name='stationparametermapping',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wis2box_adl_adcon_plugin.stationmapping', unique=True, verbose_name='Station Mapping'),
        ),
    ]
