# Generated by Django 5.0.6 on 2024-07-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_network_plugin'),
        ('wis2box_adl_adcon_plugin', '0003_alter_parametermapping_analog_tag_node_subclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmapping',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station'),
        ),
    ]
