# Generated by Django 5.0.6 on 2024-07-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_network_plugin'),
        ('wis2box_adl_adcon_plugin', '0004_alter_stationmapping_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametermapping',
            name='parameter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='stationparametermapping',
            name='parameter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wis2box_adl_adcon_plugin.parametermapping', verbose_name='Parameter Mapping'),
        ),
        migrations.AlterField(
            model_name='stationparametermapping',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wis2box_adl_adcon_plugin.stationmapping', verbose_name='Station Mapping'),
        ),
    ]
