# Generated by Django 5.0.6 on 2024-07-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_network_plugin'),
        ('wis2box_adl_adcon_plugin', '0005_alter_parametermapping_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationparametermapping',
            name='parameter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter'),
        ),
        migrations.DeleteModel(
            name='ParameterMapping',
        ),
    ]
