# Generated by Django 5.0.6 on 2024-07-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2box_adl_adcon_plugin', '0006_alter_stationparametermapping_parameter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationparametermapping',
            options={'ordering': ['station'], 'verbose_name': 'ADCON Station Parameter Mapping', 'verbose_name_plural': 'ADCON Station Parameter Mapping'},
        ),
        migrations.AlterField(
            model_name='stationparametermapping',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wis2box_adl_adcon_plugin.stationmapping', verbose_name='Station Mapping'),
        ),
    ]
