# Generated by Django 5.0.6 on 2024-07-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_network_plugin'),
        ('wis2box_adl_adcon_plugin', '0007_alter_stationparametermapping_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stationparametermapping',
            constraint=models.UniqueConstraint(fields=('station', 'parameter'), name='unique_station_parameter'),
        ),
    ]
