# Generated by Django 5.0.6 on 2024-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2box_adl_adcon_plugin', '0008_stationparametermapping_unique_station_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationparametermapping',
            name='analog_tag_node_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Analog Tag Node ID'),
        ),
    ]
