# Generated by Django 5.0.6 on 2024-07-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_network_plugin'),
        ('wis2box_adl_adcon_plugin', '0009_alter_stationparametermapping_analog_tag_node_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationparametermapping',
            options={'ordering': ['station_mapping'], 'verbose_name': 'ADCON Station Parameter Mapping', 'verbose_name_plural': 'ADCON Station Parameter Mapping'},
        ),
        migrations.RemoveConstraint(
            model_name='stationparametermapping',
            name='unique_station_parameter',
        ),
        migrations.RenameField(
            model_name='stationparametermapping',
            old_name='station',
            new_name='station_mapping',
        ),
        migrations.AddConstraint(
            model_name='stationparametermapping',
            constraint=models.UniqueConstraint(fields=('station_mapping', 'parameter'), name='unique_station_mapping_parameter'),
        ),
    ]
