# Generated by Django 5.0.6 on 2024-07-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2box_adl_adcon_plugin', '0012_stationparametermapping_last_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationparametermapping',
            name='last_imported',
        ),
        migrations.AddField(
            model_name='stationmapping',
            name='last_imported',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Imported'),
        ),
    ]
