# Generated by Django 5.0.6 on 2024-09-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_pluginexecutionevent_options'),
        ('wis2box_adl_adcon_plugin', '0013_remove_stationparametermapping_last_imported_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationmapping',
            options={'verbose_name': 'ADCON Station Link', 'verbose_name_plural': 'ADCON Stations Link'},
        ),
        migrations.AlterField(
            model_name='stationmapping',
            name='device_node_id',
            field=models.PositiveIntegerField(help_text='ADCON Device Node', unique=True, verbose_name='ADCON Device Node'),
        ),
        migrations.AlterField(
            model_name='stationmapping',
            name='station',
            field=models.OneToOneField(help_text='Station to link with ADCON', on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station'),
        ),
    ]
