# Generated by Django 5.0.6 on 2024-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2box_adl_adcon_plugin', '0014_alter_stationmapping_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationparametermapping',
            name='units',
            field=models.CharField(default='mm', max_length=10, verbose_name='Units'),
            preserve_default=False,
        ),
    ]
